# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_new_optimization_problem <- function(nrow = 1000000L, ncol = 1000000L, ncell = 100000L) {
    .Call('prioritizrutils_rcpp_new_optimization_problem', PACKAGE = 'prioritizrutils', nrow, ncol, ncell)
}

rcpp_predefined_optimization_problem <- function(l) {
    .Call('prioritizrutils_rcpp_predefined_optimization_problem', PACKAGE = 'prioritizrutils', l)
}

rcpp_get_optimization_problem_ncol <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_ncol', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_nrow <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_nrow', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_ncell <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_ncell', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_A <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_A', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_modelsense <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_modelsense', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_number_of_planning_units <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_number_of_planning_units', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_number_of_features <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_number_of_features', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_vtype <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_vtype', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_obj <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_obj', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_rhs <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_rhs', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_sense <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_sense', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_lb <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_lb', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_ub <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_ub', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_col_ids <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_col_ids', PACKAGE = 'prioritizrutils', x)
}

rcpp_get_optimization_problem_row_ids <- function(x) {
    .Call('prioritizrutils_rcpp_get_optimization_problem_row_ids', PACKAGE = 'prioritizrutils', x)
}

rcpp_add_rij_data <- function(x, rij) {
    .Call('prioritizrutils_rcpp_add_rij_data', PACKAGE = 'prioritizrutils', x, rij)
}

rcpp_apply_asymmetric_boundary_constraints <- function(x, boundary_matrix, penalty, edge_factor) {
    .Call('prioritizrutils_rcpp_apply_asymmetric_boundary_constraints', PACKAGE = 'prioritizrutils', x, boundary_matrix, penalty, edge_factor)
}

rcpp_apply_connected_constraints <- function(x, boundary_matrix) {
    .Call('prioritizrutils_rcpp_apply_connected_constraints', PACKAGE = 'prioritizrutils', x, boundary_matrix)
}

rcpp_apply_binary_decision <- function(x) {
    .Call('prioritizrutils_rcpp_apply_binary_decision', PACKAGE = 'prioritizrutils', x)
}

rcpp_apply_proportion_decision <- function(x) {
    .Call('prioritizrutils_rcpp_apply_proportion_decision', PACKAGE = 'prioritizrutils', x)
}

rcpp_apply_semicontinuous_decision <- function(x, upper) {
    .Call('prioritizrutils_rcpp_apply_semicontinuous_decision', PACKAGE = 'prioritizrutils', x, upper)
}

rcpp_apply_feature_weights <- function(x, weights) {
    .Call('prioritizrutils_rcpp_apply_feature_weights', PACKAGE = 'prioritizrutils', x, weights)
}

rcpp_apply_locked_in_constraints <- function(x, indices) {
    .Call('prioritizrutils_rcpp_apply_locked_in_constraints', PACKAGE = 'prioritizrutils', x, indices)
}

rcpp_apply_locked_out_constraints <- function(x, indices) {
    .Call('prioritizrutils_rcpp_apply_locked_out_constraints', PACKAGE = 'prioritizrutils', x, indices)
}

rcpp_apply_max_cover_objective <- function(x, abundances, costs, budget) {
    .Call('prioritizrutils_rcpp_apply_max_cover_objective', PACKAGE = 'prioritizrutils', x, abundances, costs, budget)
}

rcpp_apply_max_features_objective <- function(x, targets, costs, budget) {
    .Call('prioritizrutils_rcpp_apply_max_features_objective', PACKAGE = 'prioritizrutils', x, targets, costs, budget)
}

rcpp_apply_max_phylo_objective <- function(x, targets, costs, budget, branch_matrix, branch_lengths) {
    .Call('prioritizrutils_rcpp_apply_max_phylo_objective', PACKAGE = 'prioritizrutils', x, targets, costs, budget, branch_matrix, branch_lengths)
}

rcpp_apply_min_set_objective <- function(x, targets, costs) {
    .Call('prioritizrutils_rcpp_apply_min_set_objective', PACKAGE = 'prioritizrutils', x, targets, costs)
}

rcpp_apply_symmetric_boundary_constraints <- function(x, boundary_matrix, penalty, edge_factor) {
    .Call('prioritizrutils_rcpp_apply_symmetric_boundary_constraints', PACKAGE = 'prioritizrutils', x, boundary_matrix, penalty, edge_factor)
}

rcpp_boundary_data <- function(data, tolerance = 0.00001) {
    .Call('prioritizrutils_rcpp_boundary_data', PACKAGE = 'prioritizrutils', data, tolerance)
}

rcpp_branch_matrix <- function(x) {
    .Call('prioritizrutils_rcpp_branch_matrix', PACKAGE = 'prioritizrutils', x)
}

rcpp_list_to_matrix_indices <- function(x, n_preallocate = 10000L) {
    .Call('prioritizrutils_rcpp_list_to_matrix_indices', PACKAGE = 'prioritizrutils', x, n_preallocate)
}

rcpp_sp_to_polyset <- function(x, slot, n_preallocate = 10000L) {
    .Call('prioritizrutils_rcpp_sp_to_polyset', PACKAGE = 'prioritizrutils', x, slot, n_preallocate)
}

